Repository GuillaumeKESTEMAN/BookMyEvent, pull requests merged in 2024-10, with the labels that each got.

#16 Update README.md
  README.md
Labels: documentation

#17 Chore: install needed packages
  App.js
  package-lock.json
  package.json
Labels: packages

#25 feat: create sign up
  App.js
  package-lock.json
  package.json
  screens/SignUp/SignUp.jsx
  screens/SignUp/index.js
  shared/components/UserDataForm/UserDataForm.helpers.js
  shared/components/UserDataForm/UserDataForm.jsx
  shared/context/AppContext.js
Labels: back, front

#30 Add User page
  App.js
  pages/UserScreen/UserScreen.jsx
  pages/UserScreen/UserScreen.styles.js
  pages/UserScreen/index.js
  shared/context/AppContext.js
  shared/context/helpers/User.helpers.js
Labels: back, front

#32 Feat: manage correctly navigation
  App.js
  pages/Homescreen/Homescreen.jsx
  pages/Homescreen/index.js
  pages/UserScreen/UserScreen.jsx
  pages/UserScreen/index.js
  screens/Homescreen/Home.helpers.js
  screens/Homescreen/Home.jsx
  screens/Homescreen/Home.styles.js
  screens/Homescreen/index.js
  screens/SignIn/SignIn.jsx
  screens/SignUp/SignUp.jsx
  screens/User/User.jsx
  screens/User/User.styles.js
  screens/User/index.js
  utils/Navigator/Navigator.jsx
  utils/Navigator/index.js
Labels: front

#33 Feat: create screen view shared component
  screens/Home/Home.helpers.js
  screens/Home/Home.jsx
  screens/Home/Home.styles.js
  screens/Home/index.js
  screens/Homescreen/Home.styles.js
  screens/SignIn/SignIn.jsx
  screens/SignIn/SignIn.styles.js
  screens/SignUp/SignUp.jsx
  screens/SignUp/SignUp.styles.js
  screens/User/User.jsx
  screens/User/User.styles.js
  shared/components/ScreenView/ScreenView.jsx
  shared/components/ScreenView/ScreenView.styles.js
  shared/components/ScreenView/index.js
  shared/components/UserDataForm/UserDataForm.jsx
  utils/Navigator/Navigator.jsx
Labels: front

#36 Feat: add user update form
  App.js
  screens/User/User.jsx
  screens/User/User.navigator.jsx
  screens/User/UserUpdateForm/UserUpdateForm.jsx
  screens/User/UserUpdateForm/index.js
  screens/User/index.js
  shared/components/UserDataForm/UserDataForm.jsx
  shared/context/AppContext.js
  shared/context/helpers/User.helpers.js
  utils/Navigator/Navigator.jsx
  utils/getUsers.js
  utils/initializeData.js
Labels: back, front

#37 feat: add authentication cache
  app.json
  package-lock.json
  package.json
  shared/context/AppContext.js
  shared/context/helpers/User.helpers.js
  utils/Navigator/Navigator.jsx
Labels: back

#38 Feat/add-my-events-page
  data/initialData.json
  screens/UserEvents/UserEvents.helpers.js
  screens/UserEvents/UserEvents.jsx
  screens/UserEvents/UserEvents.styles.js
  screens/UserEvents/index.js
  shared/components/EventClickCard/EventClickCard.styles.js
  utils/Navigator/Navigator.jsx
  utils/getEvents.js
  utils/initializeData.js
Labels: front, design

#44 Create Doc
  README.md
Labels: documentation

#43 refactor: translate french to english
  screens/Home/Home.helpers.js
  screens/Home/Home.jsx
  screens/NewEvent/NewEvent.jsx
Labels: front
